///*
// * Swagger Api Demo
// * Api Demo Tech
// *
// * The version of the OpenAPI document: 1.0.0
// * Contact: apiteam@swagger.io
// *
// * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
// * https://openapi-generator.tech
// * Do not edit the class manually.
// */
//
//
//package com.demo.challengeTech.controller;
//
//import com.demo.challengeTech.ApiException;
//import com.demo.challengeTech.openAPI.dto.AgeAverageResponseDto;
//import com.demo.challengeTech.openAPI.dto.ClientDto;
//import org.junit.Test;
//import org.junit.Ignore;
//
//import java.util.ArrayList;
//import java.util.HashMap;
//import java.util.List;
//import java.util.Map;
//
///**
// * API tests for ClientApi
// */
//@Ignore
//public class ClientApiTest {
//
//    private final ClientApi api = new ClientApi();
//
//
//    /**
//     * Agrega una nueva persona como cliente
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void addPersonTest() throws ApiException {
//        ClientDto clientDto = null;
//                ClientDto response = api.addPerson(clientDto);
//        // TODO: test validations
//    }
//
//    /**
//     * Reporte con respecto a edad de Clientes
//     *
//     * Multiple status values can be provided with comma separated strings
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void getAgeReportTest() throws ApiException {
//                AgeAverageResponseDto response = api.getAgeReport();
//        // TODO: test validations
//    }
//
//    /**
//     * Listado de Clientes
//     *
//     * Multiple status values can be provided with comma separated strings
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void listClientTest() throws ApiException {
//                List<ClientDto> response = api.listClient();
//        // TODO: test validations
//    }
//
//}
